---
sources:
  - name: bter_source
    interval: 10
    meters:
      - "bter.btc"
    sinks:
      - "meter_sink"
    publishers:
      - "database://"
sinks:
    - name: meter_sink
      publishers:
        - database://
